'use client';

export default function Terms() {
  return (
    <div style={{minHeight:"100vh",background:"#FAFAF8",color:"#2C2010",fontFamily:"'DM Sans',sans-serif",padding:"60px 24px 100px",maxWidth:680,margin:"0 auto",lineHeight:1.8}}>
      <a href="/" style={{display:"inline-block",marginBottom:40,fontSize:13,color:"#C9A96E",textDecoration:"none",letterSpacing:1}}>← Back to Nuette</a>
      <h1 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:38,fontWeight:300,color:"#2C2010",marginBottom:8}}>Terms of Service</h1>
      <p style={{fontSize:13,color:"#8a8070",marginBottom:40}}>Last updated: February 26, 2026</p>

      <p>Welcome to Nuette. By accessing or using our application ("App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the App.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>1. About Nuette</h2>
      <p>Nuette is a sleep training support application that provides AI-powered coaching through a virtual assistant named Luna. Luna offers guidance, encouragement, and information related to infant sleep training methods.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>2. Not Medical Advice</h2>
      <p><strong>Luna is not a doctor, nurse, pediatrician, or licensed medical professional.</strong> The information provided through Nuette is for informational and supportive purposes only and should not be considered medical advice. Always consult your pediatrician or healthcare provider before starting any sleep training program, especially if your child has medical conditions, feeding concerns, or developmental considerations. Never disregard professional medical advice or delay seeking it because of something you read or received through Nuette.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>3. Eligibility</h2>
      <p>You must be at least 18 years of age to create an account and use Nuette. By using the App, you represent that you are at least 18 years old and are the parent or legal guardian of the child for whom you are seeking sleep training support.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>4. Account Registration</h2>
      <p>To use Nuette, you must create an account with a valid email address and password. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Please notify us immediately at <a href="mailto:support@nuette.app" style={{color:"#C9A96E"}}>support@nuette.app</a> if you suspect unauthorized access to your account.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>5. Acceptable Use</h2>
      <p>You agree to use Nuette only for its intended purpose: supporting your family's sleep training journey. You agree not to misuse the App, attempt to access it through unauthorized means, or use it in any way that could harm, disable, or impair the service.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>6. AI-Generated Content</h2>
      <p>Luna's responses are generated by artificial intelligence. While we strive to provide accurate, helpful, and evidence-based guidance, AI-generated content may occasionally contain errors or may not be appropriate for every situation. You acknowledge that Luna's responses are generated in real time and may vary. Nuette does not guarantee the accuracy, completeness, or suitability of any information provided by Luna.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>7. Intellectual Property</h2>
      <p>All content, design, branding, and code associated with Nuette — including the name "Nuette," the Luna character, and all visual elements — are the property of Nuette and are protected by applicable intellectual property laws. You may not copy, modify, distribute, or create derivative works from any part of the App without prior written consent.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>8. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, Nuette and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the App. This includes, but is not limited to, any decisions made based on information provided by Luna. Your use of Nuette is at your own risk.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>9. Termination</h2>
      <p>We reserve the right to suspend or terminate your account at any time, with or without notice, for conduct that we determine violates these Terms or is harmful to other users, us, or third parties. You may delete your account at any time by contacting <a href="mailto:support@nuette.app" style={{color:"#C9A96E"}}>support@nuette.app</a>.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>10. Changes to These Terms</h2>
      <p>We may update these Terms from time to time. If we make material changes, we will notify you through the App or by email. Your continued use of Nuette after changes are posted constitutes your acceptance of the revised Terms.</p>

      <h2 style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:400,marginTop:40,marginBottom:12,color:"#2C2010"}}>11. Contact Us</h2>
      <p>If you have questions about these Terms, please contact us at <a href="mailto:hello@nuette.app" style={{color:"#C9A96E"}}>hello@nuette.app</a>.</p>

      <div style={{marginTop:60,paddingTop:24,borderTop:"1px solid rgba(201,169,110,0.15)",fontSize:12,color:"#c4beb5",textAlign:"center"}}>© 2026 Nuette. All rights reserved.</div>
    </div>
  );
}
